/*export*/ const products = [
  {
    title: "Magnetite",
    category: 1,
    price: 89.0,
    img: "https://www.tenhomaisdiscosqueamigos.com/wp-content/uploads/2017/08/scalene-magnetite-capa-700-696x696.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "https://gomagringa.com/cdn/shop/products/novoschorare01_1200x.jpg?v=1591909552",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nevermind",
    category: 8,
    price: 50.0,
    img: "https://upload.wikimedia.org/wikipedia/pt/3/3f/Nevermind.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "https://upload.wikimedia.org/wikipedia/en/8/8d/Both_Sides_%28Phil_Collins%29.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
];

/*export*/ const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
